spring: 
  profiles:
    active: test
    

---
server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.qin.springcloud.bean
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring的配置
spring:
  profiles: dev
  application:
    name: springcloud-provider-users
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/user1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: springcloud-provider-users8001 # 修改eureka上的默认描述信息！
    ip-address: 127.3.1.3
  
#info配置
info:
  app.name: qin-springcloud
  company.name: qin-springcloud.com
 
---
server:
  port: 8002

#mybatis配置
mybatis:
  type-aliases-package: com.qin.springcloud.bean
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring的配置
spring:
  profiles: test
  application:
    name: springcloud-provider-users
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/user2?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: springcloud-provider-users8002 # 修改eureka上的默认描述信息！
    ip-address: 127.3.1.3
  
#info配置
info:
  app.name: qin-springcloud
  company.name: qin-springcloud.com
